# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

env:
  global:
    - LINTR_COMMENT_BOT=false

addons:
  apt:
    packages:
    - libudunits2-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - libnetcdf-dev
    - netcdf-bin

sudo: false

warnings_are_errors: false # set to true: This option forces all WARNINGS from R CMD check
  # to become build failures (default true). This is especially helpful when preparing
  # your package for submission to CRAN

# Vignette `rSOILWAT2_demo` only works locally
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

cache: packages

after_success:
  # code coverage but exclude all SOILWAT2 submodule files in scr/
  - Rscript -e 'covr::coveralls(line_exclusions = as.list(file.path("src", list.files("src", recursive = TRUE))))'

